# Site settings
title:       Johny Nogueira
email:       johnynogueira1@gmail.com
author:      Johny Nogueira
description: "Johny Nogueira personal website"
baseurl:     "https://github.com/JohnyNogueira/johnynogueira.github.io"
url:         "http://johnynogueira.github.io"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:     "johnynogueira"

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username:      "johnynogueira"
bitbucket_username:
stackoverflow_id:
twitter_username:     "johnyop_"
google_plus_id:       "https://plus.google.com/+JohnyNogueira1"
linkedin_username:    "https://www.linkedin.com/in/johnynogueira"
angellist_username:
medium_id:            "@johnynogueira"
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
